[theme]
base = "dark"
primaryColor = "#FF7849"
backgroundColor = "#0A0A0E"
secondaryBackgroundColor = "#101016"
textColor = "#ECECF1"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
